COUNTRIES = (
    ("AF", "Afghanistan"),
    ("AL", "Albanie"),
    ("DZ", "Algérie"),
    ("AD", "Andorre"),
    ("AO", "Angola"),
    ("AR", "Argentine"),
    ("AM", "Arménie"),
    ("AU", "Australie"),
    ("AT", "Autriche"),
    ("AZ", "Azerbaïdjan"),
    ("BH", "Bahreïn"),
    ("BD", "Bangladesh"),
    ("BY", "Biélorussie"),
    ("BE", "Belgique"),
    ("BJ", "Bénin"),
    ("BO", "Bolivie"),
    ("BR", "Brésil"),
    ("BG", "Bulgarie"),
    ("BF", "Burkina Faso"),
    ("BI", "Burundi"),
    ("CM", "Cameroun"),
    ("CA", "Canada"),
    ("CF", "République centrafricaine"),
    ("TD", "Tchad"),
    ("CL", "Chili"),
    ("CN", "Chine"),
    ("CO", "Colombie"),
    ("CG", "Congo"),
    ("CD", "Congo (RDC)"),
    ("CR", "Costa Rica"),
    ("CI", "Côte d'Ivoire"),
    ("HR", "Croatie"),
    ("CU", "Cuba"),
    ("CY", "Chypre"),
    ("CZ", "République tchèque"),
    ("DK", "Danemark"),
    ("DJ", "Djibouti"),
    ("EG", "Égypte"),
    ("ES", "Espagne"),
    ("FR", "France"),
    ("DE", "Allemagne"),
    ("GH", "Ghana"),
    ("GR", "Grèce"),
    ("IN", "Inde"),
    ("ID", "Indonésie"),
    ("IR", "Iran"),
    ("IQ", "Irak"),
    ("IE", "Irlande"),
    ("IT", "Italie"),
    ("JP", "Japon"),
    ("KE", "Kenya"),
    ("KW", "Koweït"),
    ("LB", "Liban"),
    ("LY", "Libye"),
    ("LU", "Luxembourg"),
    ("MG", "Madagascar"),
    ("MW", "Malawi"),
    ("MY", "Malaisie"),
    ("ML", "Mali"),
    ("MX", "Mexique"),
    ("MA", "Maroc"),
    ("MZ", "Mozambique"),
    ("NA", "Namibie"),
    ("NP", "Népal"),
    ("NL", "Pays-Bas"),
    ("NZ", "Nouvelle-Zélande"),
    ("NG", "Nigeria"),
    ("NO", "Norvège"),
    ("OM", "Oman"),
    ("PK", "Pakistan"),
    ("PS", "Palestine"),
    ("PA", "Panama"),
    ("PY", "Paraguay"),
    ("PE", "Pérou"),
    ("PH", "Philippines"),
    ("PL", "Pologne"),
    ("PT", "Portugal"),
    ("QA", "Qatar"),
    ("RO", "Roumanie"),
    ("RU", "Russie"),
    ("RW", "Rwanda"),
    ("SA", "Arabie saoudite"),
    ("SN", "Sénégal"),
    ("RS", "Serbie"),
    ("SG", "Singapour"),
    ("SK", "Slovaquie"),
    ("SI", "Slovénie"),
    ("ZA", "Afrique du Sud"),
    ("KR", "Corée du Sud"),
    ("ES", "Espagne"),
    ("LK", "Sri Lanka"),
    ("SD", "Soudan"),
    ("SE", "Suède"),
    ("CH", "Suisse"),
    ("SY", "Syrie"),
    ("TZ", "Tanzanie"),
    ("TH", "Thaïlande"),
    ("TG", "Togo"),
    ("TN", "Tunisie"),
    ("TR", "Turquie"),
    ("UA", "Ukraine"),
    ("AE", "Émirats arabes unis"),
    ("GB", "Royaume-Uni"),
    ("US", "États-Unis"),
    ("UY", "Uruguay"),
    ("UZ", "Ouzbékistan"),
    ("VE", "Venezuela"),
    ("VN", "Vietnam"),
    ("YE", "Yémen"),
    ("ZM", "Zambie"),
    ("ZW", "Zimbabwe"),
)

CATEGORY_TYPE = (
    ('mensuel', 'Mensuel'),
    ('journalier', 'Journalier')
)

SUBJECT_LIST = (
    ('Programmation d\'une visite', 'Programmation d\'une visite'),
    ("Plus d'information", "Plus d'information"),
    ("Réservation du bien", "Réservation du bien"),
)
