# Generated by Django 5.1.6 on 2025-03-03 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'immeuble")),
                ('cooling', models.CharField(max_length=50, verbose_name='Refroidissement')),
                ('heater', models.CharField(max_length=50, verbose_name='Rechauffement')),
                ('new', models.BooleanField(verbose_name='Nouvelle construction')),
                ('nb_garage', models.PositiveIntegerField(verbose_name='Espace du garage')),
                ('materials', models.CharField(max_length=255, verbose_name='Matériel de construction(brièvement)')),
            ],
            options={
                'verbose_name': 'Bâtiment',
                'verbose_name_plural': 'Bâtiments',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='Nom')),
                ('category_type', models.CharField(choices=[('mensuel', 'Mensuel'), ('journalier', 'Journalier')], max_length=15, null=True, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=175)),
                ('image', models.ImageField(upload_to='properties', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('bedrooms', models.PositiveIntegerField(verbose_name='Chambres')),
                ('bathrooms', models.PositiveIntegerField(verbose_name='Douches')),
                ('rooms', models.PositiveIntegerField(verbose_name='Pièces')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix')),
                ('country', models.CharField(choices=[('AF', 'Afghanistan'), ('AL', 'Albanie'), ('DZ', 'Algérie'), ('AD', 'Andorre'), ('AO', 'Angola'), ('AR', 'Argentine'), ('AM', 'Arménie'), ('AU', 'Australie'), ('AT', 'Autriche'), ('AZ', 'Azerbaïdjan'), ('BH', 'Bahreïn'), ('BD', 'Bangladesh'), ('BY', 'Biélorussie'), ('BE', 'Belgique'), ('BJ', 'Bénin'), ('BO', 'Bolivie'), ('BR', 'Brésil'), ('BG', 'Bulgarie'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CM', 'Cameroun'), ('CA', 'Canada'), ('CF', 'République centrafricaine'), ('TD', 'Tchad'), ('CL', 'Chili'), ('CN', 'Chine'), ('CO', 'Colombie'), ('CG', 'Congo'), ('CD', 'Congo (RDC)'), ('CR', 'Costa Rica'), ('CI', "Côte d'Ivoire"), ('HR', 'Croatie'), ('CU', 'Cuba'), ('CY', 'Chypre'), ('CZ', 'République tchèque'), ('DK', 'Danemark'), ('DJ', 'Djibouti'), ('EG', 'Égypte'), ('FR', 'France'), ('DE', 'Allemagne'), ('GH', 'Ghana'), ('GR', 'Grèce'), ('IN', 'Inde'), ('ID', 'Indonésie'), ('IR', 'Iran'), ('IQ', 'Irak'), ('IE', 'Irlande'), ('IT', 'Italie'), ('JP', 'Japon'), ('KE', 'Kenya'), ('KW', 'Koweït'), ('LB', 'Liban'), ('LY', 'Libye'), ('LU', 'Luxembourg'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('MY', 'Malaisie'), ('ML', 'Mali'), ('MX', 'Mexique'), ('MA', 'Maroc'), ('MZ', 'Mozambique'), ('NA', 'Namibie'), ('NP', 'Népal'), ('NL', 'Pays-Bas'), ('NZ', 'Nouvelle-Zélande'), ('NG', 'Nigeria'), ('NO', 'Norvège'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PS', 'Palestine'), ('PA', 'Panama'), ('PY', 'Paraguay'), ('PE', 'Pérou'), ('PH', 'Philippines'), ('PL', 'Pologne'), ('PT', 'Portugal'), ('QA', 'Qatar'), ('RO', 'Roumanie'), ('RU', 'Russie'), ('RW', 'Rwanda'), ('SA', 'Arabie saoudite'), ('SN', 'Sénégal'), ('RS', 'Serbie'), ('SG', 'Singapour'), ('SK', 'Slovaquie'), ('SI', 'Slovénie'), ('ZA', 'Afrique du Sud'), ('KR', 'Corée du Sud'), ('ES', 'Espagne'), ('LK', 'Sri Lanka'), ('SD', 'Soudan'), ('SE', 'Suède'), ('CH', 'Suisse'), ('SY', 'Syrie'), ('TZ', 'Tanzanie'), ('TH', 'Thaïlande'), ('TG', 'Togo'), ('TN', 'Tunisie'), ('TR', 'Turquie'), ('UA', 'Ukraine'), ('AE', 'Émirats arabes unis'), ('GB', 'Royaume-Uni'), ('US', 'États-Unis'), ('UY', 'Uruguay'), ('UZ', 'Ouzbékistan'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('YE', 'Yémen'), ('ZM', 'Zambie'), ('ZW', 'Zimbabwe')], max_length=75, verbose_name='Pays')),
                ('city', models.CharField(max_length=75, verbose_name='Ville')),
                ('address', models.CharField(max_length=100, verbose_name='Adresse')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponibe ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.buildings', verbose_name='Bâtiment')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.categories', verbose_name='Catégorie')),
                ('options', models.ManyToManyField(to='properties.options')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
            },
        ),
    ]
