# Generated by Django 5.1.6 on 2025-03-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='surface',
            field=models.PositiveIntegerField(default=35, verbose_name='Surface'),
        ),
    ]
