# Generated by Django 5.1.6 on 2025-03-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_properties_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_type',
            field=models.CharField(blank=True, choices=[('mensuel', 'Mensuel'), ('journalier', 'Journalier')], max_length=15, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix'),
        ),
    ]
