# Generated by Django 5.1.6 on 2025-03-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_categories_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='surface',
            field=models.PositiveIntegerField(verbose_name='Surface'),
        ),
    ]
