# Generated by Django 5.1.6 on 2025-03-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_properties_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='floor',
            field=models.PositiveIntegerField(default=1, verbose_name='Étage'),
        ),
    ]
