# Generated by Django 5.1.6 on 2025-03-06 17:04

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_rename_firstname_messages_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Veuillez entrez un numéro de téléphone valide'}, max_length=128, null=True, region=None),
        ),
    ]
