# Generated by Django 5.1.6 on 2025-03-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_messages_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='options',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Description'),
        ),
    ]
