# Generated by Django 5.1.6 on 2025-03-07 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_messages_options_alter_options_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery', verbose_name='Image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.properties', verbose_name='Propriété')),
            ],
            options={
                'verbose_name': "Galerie d'images",
                'verbose_name_plural': "Galerie d'images",
            },
        ),
    ]
