# Generated by Django 5.1.6 on 2025-03-07 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_propertygallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.buildings', verbose_name='Bâtiment'),
        ),
        migrations.AlterField(
            model_name='propertygallery',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeries', to='properties.properties', verbose_name='Propriété'),
        ),
    ]
